DROP DATABASE IF EXISTS ESHOPPING;
CREATE DATABASE ESHOPPING;
USE ESHOPPING;
CREATE TABLE USER
(
USER_ID INT PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(50) UNIQUE,
PASSWORD VARCHAR(50) UNIQUE,
); 